"""add uniq param 

Revision ID: 661b520d5bb7
Revises: d07c73373b2e
Create Date: 2024-05-20 00:28:21.404166

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '661b520d5bb7'
down_revision = 'd07c73373b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'bills',
        'value',
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.create_unique_constraint(None, 'bills', ['currency_id', 'value'])
    op.create_unique_constraint(None, 'currencies', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'transaction_bills',
        'quantity',
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_constraint(None, 'currencies', type_='unique')
    op.drop_constraint(None, 'bills', type_='unique')

    # ### end Alembic commands ###
